const masterBank = {
  "math": [

  {q: "Solve for x: x² - 5x + 6 = 0.", a: "2, 3", options: ["1, 6", "2, 3", "-2, -3", "5, 1"]},
  {q: "Find the roots of the equation: x² + 7x + 10 = 0.", a: "-2, -5", options: ["2, 5", "-2, -5", "-2, 5", "2, -5"]},
  {q: "What is the discriminant (D) of the equation x² - 4x + 4 = 0?", a: "0", options: ["4", "8", "0", "16"]},
  {q: "Find the value of k if x² + kx + 9 = 0 has equal roots.", a: "6 or -6", options: ["3", "6 or -6", "9", "0"]},
  {q: "If one root of x² - 3x + c = 0 is 2, find the value of c.", a: "2", options: ["1", "2", "3", "4"]},
  {q: "Solve by completing the square: x² + 6x = 7.", a: "1, -7", options: ["1, 7", "1, -7", "-1, 7", "-1, -7"]},
  {q: "Find the sum of the roots of the equation 2x² - 8x + 5 = 0.", a: "4", options: ["2", "4", "-4", "5/2"]},
  {q: "Find the product of the roots of the equation 3x² + 2x - 9 = 0.", a: "-3", options: ["3", "-3", "-2/3", "9"]},
  {q: "Form a quadratic equation whose roots are 3 and -1.", a: "x² - 2x - 3 = 0", options: ["x² + 2x - 3 = 0", "x² - 2x - 3 = 0", "x² - 4x + 3 = 0", "x² + 4x + 3 = 0"]},
  {q: "The roots of 4x² - 12x + 9 = 0 are ______.", a: "Real and Equal", options: ["Real and Distinct", "Real and Equal", "Imaginary", "Negative"]},
  {q: "Solve for x: 2x² = 32.", a: "4, -4", options: ["4", "16", "4, -4", "8, -8"]},
  {q: "If (x-3)(x+4) = 0, find the values of x.", a: "3, -4", options: ["3, 4", "-3, -4", "3, -4", "-3, 4"]},
  {q: "Find the values of x for which x² - 9 = 0.", a: "3, -3", options: ["9", "3", "3, -3", "0"]},
  {q: "Solve x² - x - 12 = 0.", a: "4, -3", options: ["4, 3", "-4, 3", "4, -3", "-4, -3"]},
  {q: "Find the vertex of the parabola y = x² - 2x + 1.", a: "(1, 0)", options: ["(0, 1)", "(1, 0)", "(-1, 0)", "(1, 1)"]},
  {q: "What is the coefficient of x in the expansion of (x-5)²?", a: "-10", options: ["5", "-5", "10", "-10"]},
  {q: "Solve 3x² + 5x - 2 = 0.", a: "1/3, -2", options: ["1/3, 2", "-1/3, 2", "1/3, -2", "-1/3, -2"]},
  {q: "If the product of two consecutive integers is 20, find the integers.", a: "4, 5", options: ["2, 10", "4, 5", "5, 6", "1, 20"]},
  {q: "Find 'a' if ax² - 4x + 1 = 0 has a root x=1.", a: "3", options: ["1", "2", "3", "4"]},
  {q: "The discriminant of 2x² - 5x - 3 = 0 is ______.", a: "49", options: ["1", "25", "49", "13"]},
  {q: "Express 302.10495 correct to five significant figures.", a: "302.10", options: ["302.10", "302.11", "302.105", "302.1049"]},
  {q: "In 1995, the enrollments of two schools X and Y were 1,050 and 1,190 respectively. Find the ratio of the enrollments of X to Y.", a: "15 : 17", options: ["50 : 11", "15 : 17", "13 : 55", "12 : 11"]},
  {q: "Convert 35 (base 10) to a number in base 2.", a: "100011", options: ["1011", "10011", "100011", "11001"]},
  {q: "The nth term of a sequence is T_n = 5 + (n - 1)^2. Evaluate T_4 - T_6.", a: "-16", options: ["30", "16", "-16", "-30"]},
  {q: "Mr. Manu travelled from Accra to Pamfokrom a distance of 720km in 8 hours. What will be his speed in m/s?", a: "25m/s", options: ["25m/s", "150m/s", "250m/s", "500m/s"]},
  {q: "If #2,500.00 amounted to #3,500.00 in 4 years at simple interest. Find the rate at which the interest was charged.", a: "10%", options: ["5%", "7 1/2%", "8%", "10%"]},
  {q: "Solve for x in the equation: 1/x + 2/3x = 1/3.", a: "5", options: ["5", "4", "3", "1"]},
  {q: "Simplify: (54k^2 - 6) / (3k + 1).", a: "6(3k - 1)", options: ["6(1 - 3k^2)", "6(3k^2 - 1)", "6(3k - 1)", "6(1 - 3k)"]},
  {q: "Make p the subject of the relationship: q = 3p/r + s/2.", a: "(2qr - rs) / 6", options: ["(2q - rs) / 6", "2qr - sr - 3", "(2qr - s) / 6", "(2qr - rs) / 6"]},
  {q: "If x + y = 2y - x + 1 = 5, find the value of x.", a: "3", options: ["3", "2", "1", "-1"]},
  {q: "The sum of 12 and one third of n is 1 more than twice n. Express this statement in the form of an equation.", a: "3n - 12 = 0", options: ["12n - 6 = 0", "3n - 12 = 0", "2n - 35 = 0", "5n - 33 = 0"]},
  {q: "The curved surface area of a cylindrical tin is 704cm². If the radius of its base is 8cm, find the height. [Take π = 22/7]", a: "14cm", options: ["14cm", "9cm", "8cm", "7cm"]},
  {q: "A sector of a circle which subtends 172° at the centre of the circle has a perimeter of 600cm. Find, correct to the nearest cm, the radius of the circle. [Take π = 22/7]", a: "120cm", options: ["120cm", "116cm", "107cm", "100cm"]},
  {q: "If the mean of the numbers 10, 14, x, 11, 13 is x, find the value of x.", a: "12", options: ["15", "14", "13", "12"]},
  {q: "Evaluate ∫ 3x^-4 dx.", a: "-x^-3 + C", options: ["(3x^-5)/-5 + C", "-3x^-3 + C", "-x^-3 + C", "-12x^-3 + C"]},
  {q: "Find the range of the following: 23, 72, 51, 61, 42, 34, 22, 52.", a: "50", options: ["22", "25", "34", "50"]},
  {q: "If the volume of a rectangular-based pyramid is 60 cm³ and its base area is 18 cm², calculate the height of the pyramid.", a: "10 cm", options: ["10 cm", "15 cm", "20 cm", "30 cm"]},
  {q: "Find the gradient of a line joining the points A(-5, 8) and B(11, -2).", a: "-5/8", options: ["-8/5", "-5/8", "5/8", "8/5"]},
  {q: "Calculate the surface area of a sphere with radius 3.5 cm. [Take π = 22/7]", a: "154 cm²", options: ["616 cm²", "308 cm²", "179⅔ cm²", "154 cm²"]},
  {q: "If log10(6x-4) - log10 2 = 1, solve for x.", a: "4", options: ["2", "3", "4", "5"]},
  {q: "Simplify: √108 + √125 - √75.", a: "√3 + 5√5", options: ["√3 + 5√5", "6√3 - 5√5", "6√3 + √2", "6√3 - √2"]},
  {q: "Evaluate: (64^½ + 125^⅓)².", a: "169", options: ["121", "144", "169", "196"]},
  {q: "If y varies inversely as the square of x. If x = 3 when y = 100, find the equation connecting x and y.", a: "yx² = 900", options: ["yx² = 300", "yx² = 900", "y = 100x/9", "y = 900x"]},
  {q: "Simplify: 2¼ × 3½ ÷ 4⅝.", a: "1 ⅗", options: ["⅗", "1 ⅗", "1 ¼", "1 ⅘"]},
  {q: "If F = 9/5C + 32, find C when F = 98.6.", a: "37", options: ["30", "37", "39", "41"]},
  {q: "If y + 2x = 4 and y - 3x = -1, find the value of (x + y).", a: "3", options: ["3", "2", "1", "-1"]},
  {q: "Simplify: (2 - 18m²) / (1 + 3m).", a: "2(1 - 3m)", options: ["2(1 + 3m)", "2(2 + 3m²)", "2(1 - 3m)", "2(1 - 3m²)"]},
  {q: "Find the median of 2, 1, 0, 3, 1, 1, 4, 0, 1 and 2.", a: "1.0", options: ["0.0", "0.5", "1.0", "1.5"]},
  {q: "The volume of a cylindrical tank, 10m high is 385m³. Find the diameter of the tank. [Take π = 22/7]", a: "7m", options: ["14m", "10m", "7m", "5m"]},
  {q: "Solve the equation 2x² - x - 6 = 0.", a: "x = -3/2 or 2", options: ["x = -3/2 or 2", "x = -2 or 3/2", "x = -3 or 2", "x = 3 or -2"]},
  {q: "Find the value of x for which (x-5) / x(x-1) is undefined.", a: "0 or 1", options: ["0 or 5", "-5 or 5", "-1 or 5", "0 or 1"]},
  {q: "Find the nth term of the sequence 2×3, 4×6, 8×9, 16×12...", a: "2ⁿ×3n", options: ["2ⁿ×3(n+1)", "2ⁿ×3n", "2ⁿ×3ⁿ", "2ⁿ⁺¹×3n"]},
  {q: "If 3x ≡ 4 (mod 5), find the least positive value of x.", a: "3", options: ["1", "2", "3", "4"]},
  {q: "The total surface area of a hemisphere is 75π cm². Find the radius.", a: "5.0cm", options: ["5.0cm", "7.0cm", "8.5cm", "12.0cm"]},
  
  // AP Questions
  {q: "Find the 10th term of the AP: 2, 5, 8, 11...", a: "29", options: ["27", "29", "31", "33"]},
  {q: "The first term of an AP is 5 and the common difference is 3. Find the sum of the first 12 terms.", a: "258", options: ["258", "210", "300", "245"]},
  {q: "In an AP, the 4th term is 13 and the 10th term is 31. Find the common difference.", a: "3", options: ["2", "3", "4", "5"]},
  {q: "How many terms are in the AP: 7, 13, 19, ..., 151?", a: "25", options: ["23", "24", "25", "26"]},
  {q: "Find the sum of the first 20 even numbers.", a: "420", options: ["400", "420", "440", "460"]},
  {q: "The nth term of a sequence is given by 3n + 1. Find the 5th term.", a: "16", options: ["13", "15", "16", "18"]},
  {q: "If 2x, 5x-1, and 6x+2 are in AP, find the value of x.", a: "2", options: ["1", "2", "3", "4"]},
  {q: "Find the sum of the AP: 1, 3, 5, ..., 99.", a: "2500", options: ["2450", "2500", "2550", "2600"]},
  {q: "The first term of an AP is 10 and the last term is 50. If the sum is 300, find the number of terms.", a: "10", options: ["8", "10", "12", "15"]},
  {q: "What is the common difference of the AP: 10, 7, 4, 1...?", a: "-3", options: ["3", "-3", "2", "-2"]},
  {q: "In triangle ABC, a=5, A=30°, B=45°. Find side b using Sine Rule.", a: "7.07", options: ["5.5", "7.07", "8.1", "10.0"]},
  {q: "Find the value of sin(60°) in surd form.", a: "√3/2", options: ["1/2", "√2/2", "√3/2", "1"]},
  {q: "If cos θ = 4/5, find tan θ.", a: "3/4", options: ["3/5", "3/4", "4/3", "5/4"]},
  {q: "In a right-angled triangle, if the opposite side is 3 and the adjacent is 4, find the hypotenuse.", a: "5", options: ["5", "6", "7", "25"]},
  {q: "Find the value of tan(45°).", a: "1", options: ["0", "1/2", "1", "√3"]},
  {q: "The Sine Rule is expressed as ______.", a: "a/sinA = b/sinB", options: ["a/cosA = b/cosB", "a/sinA = b/sinB", "a² = b² + c²", "sin²θ + cos²θ = 1"]},
  {q: "What is sin(90°)?", a: "1", options: ["0", "0.5", "1", "Undefined"]},
  {q: "If sin θ = 0.5, find the acute angle θ.", a: "30°", options: ["30°", "45°", "60°", "90°"]},
  {q: "Find the area of a triangle with sides 4cm, 6cm and included angle 30°.", a: "6 cm²", options: ["6 cm²", "12 cm²", "24 cm²", "3 cm²"]},
  {q: "In triangle PQR, p=10, sinP=0.5, sinQ=0.8. Find side q.", a: "16", options: ["12", "14", "16", "18"]},
  {q: "The identity sin²θ + cos²θ is equal to ______.", a: "1", options: ["0", "1", "tanθ", "2"]},
  {q: "Find the value of cos(180°).", a: "-1", options: ["0", "1", "-1", "0.5"]},
  {q: "In a right-angled triangle, sin θ is defined as ______.", a: "Opposite / Hypotenuse", options: ["Adjacent / Hypotenuse", "Opposite / Adjacent", "Opposite / Hypotenuse", "Hypotenuse / Opposite"]},
  {q: "Find side c in triangle ABC if a=8, b=10, C=60° using Cosine Rule.", a: "9.17", options: ["8.50", "9.17", "10.2", "12.0"]},
  {q: "What is the value of tan(60°)?", a: "√3", options: ["1/√3", "1", "√3", "2"]},
  {q: "A ladder 10m long leans against a wall making an angle of 60° with the ground. How high is the wall?", a: "8.66m", options: ["5m", "8.66m", "10m", "7.5m"]},
  {q: "If tan θ = 1, find sin θ.", a: "√2/2", options: ["1/2", "√2/2", "√3/2", "1"]},
  {q: "Find the period of the function y = sin(x).", a: "360°", options: ["90°", "180°", "360°", "720°"]},
  {q: "In triangle ABC, if sin A = 1/2, sin B = 1/3 and a = 12, find b.", a: "8", options: ["6", "8", "10", "12"]},
  {q: "What is the value of cos(0°)?", a: "1", options: ["0", "0.5", "1", "-1"]},
  {q: "Solve for x and y: x + y = 10 and x - y = 4.", a: "x=7, y=3", options: ["x=6, y=4", "x=7, y=3", "x=8, y=2", "x=5, y=5"]},
  {q: "Find the values of x and y: 2x + y = 7 and x + 2y = 5.", a: "x=3, y=1", options: ["x=2, y=3", "x=3, y=1", "x=1, y=5", "x=4, y=-1"]},
  {q: "Solve the system: 3x - 2y = 8 and x + y = 6.", a: "x=4, y=2", options: ["x=4, y=2", "x=2, y=4", "x=5, y=1", "x=3, y=3"]},
  {q: "Find x and y if: 4x + 3y = 18 and x - y = 1.", a: "x=3, y=2", options: ["x=4, y=1", "x=2, y=3", "x=3, y=2", "x=5, y=-1"]},
  {q: "Solve: 5x + 2y = 16 and 3x - y = 3.", a: "x=2, y=3", options: ["x=2, y=3", "x=3, y=1", "x=4, y=-2", "x=1, y=5.5"]},
  {q: "If 2x + 3y = 13 and x + y = 5, what is the value of x?", a: "2", options: ["1", "2", "3", "4"]},
  {q: "Solve for y: 6x - y = 11 and 2x + 3y = 7.", a: "1", options: ["1", "2", "3", "-1"]},
  {q: "The sum of two numbers is 15 and their difference is 3. Find the numbers.", a: "9 and 6", options: ["10 and 5", "8 and 7", "9 and 6", "11 and 4"]},
  {q: "Solve the equations: x/2 + y/3 = 5 and x - y = 0.", a: "x=6, y=6", options: ["x=4, y=4", "x=6, y=6", "x=3, y=3", "x=12, y=12"]},
  {q: "Find the point of intersection for the lines y = 2x + 1 and y = -x + 4.", a: "(1, 3)", options: ["(1, 3)", "(2, 5)", "(0, 4)", "(3, 1)"]},
  // GP Questions
  {q: "Find the 6th term of the GP: 3, 6, 12, 24...", a: "96", options: ["48", "72", "96", "120"]},
  {q: "The first term of a GP is 5 and the common ratio is 2. Find the 4th term.", a: "40", options: ["20", "30", "40", "80"]},
  {q: "Find the sum to infinity of the GP: 1, 1/2, 1/4, 1/8...", a: "2", options: ["1.5", "2", "2.5", "Infinity"]},
  {q: "The 3rd term of a GP is 18 and the 4th term is 54. Find the common ratio.", a: "3", options: ["2", "3", "4", "6"]},
  {q: "Find the geometric mean of 4 and 16.", a: "8", options: ["6", "8", "10", "12"]},
  {q: "If x, 4, 16 are in GP, find the value of x.", a: "1", options: ["1", "2", "4", "8"]},
  {q: "Find the sum of the first 5 terms of the GP: 2, 4, 8...", a: "62", options: ["30", "32", "62", "64"]},
  {q: "The sum to infinity of a GP is 12. If the first term is 4, find the common ratio.", a: "2/3", options: ["1/3", "1/2", "2/3", "3/4"]},
  {q: "Find the 5th term of the GP: 100, 50, 25...", a: "6.25", options: ["12.5", "6.25", "3.125", "1.56"]},
  {q: "What is the common ratio of the GP: 1/3, 1, 3, 9...?", a: "3", options: ["1/3", "2", "3", "9"]},
  
  {q: "Find the mean deviation of 20, 30, 25, 40, 35, 50, 45, 40, 20 and 45.", a: "9", options: ["8", "9", "10", "12"]},
  {q: "Express 0.612 in the form x/y where x and y are integers.", a: "68/111", options: ["153/250", "68/111", "61/100", "21/33"]},
  {q: "If n(U) = 40, n(M) = 28, n(N) = 20 and n(M ∪ N) = 40, find n(M ∩ N)'.", a: "32", options: ["18", "20", "30", "32"]},
  {q: "Find the inter-quartile range of 1, 3, 4, 5, 8, 9, 10, 11, 12, 14, 16.", a: "7", options: ["6", "7", "8", "9"]},
  {q: "Solve for x if 25^(3x + 2) = 5^(x + 1).", a: "-3/5", options: ["-3/5", "1/5", "-1", "0"]},
  {q: "Calculate the variance of the following data: 2, 3, 5, 6.", a: "2.50", options: ["4.00", "2.50", "2.00", "1.58"]},
  {q: "If tan x = 4/3 and 0° < x < 90°, find the value of sin x - cos x.", a: "1/5", options: ["1/10", "1/5", "5/12", "1 ⅖"]},
  {q: "Calculate the standard deviation of the following set of numbers: 9, 8, 7, 6, 4.", a: "1.87", options: ["2.38", "4.38", "1.87", "6.58"]},
  {q: "Solve: (27/125)^-⅓ × (4/9)^½.", a: "10/9", options: ["10/9", "9/10", "2/5", "12/125"]},
  {q: "Factorise completely: 32x²y - 48x³y³.", a: "16x²y(2 - 3xy²)", options: ["16x²y(2 - 3xy²)", "8xy(4x - 6x²y²)", "8x²y(4 - 6xy²)", "16xy(2x - 3x²y²)"]},
  {q: "The dimensions of a square are given as 6.25 cm. If a student measured it as 6.12 cm, find the percentage error in the area.", a: "4.12%", options: ["2.08%", "4.12%", "5.00%", "1.50%"]}
],

 "english": [
  {q: "From the options lettered A to D, choose the word that best completes the sentence: The company's performance was ______ by the board.", a: "commended", options: ["commended", "recommended", "commanded", "demanded"]},
  {q: "If you don't stop playing, you ______ your exams.", a: "will fail", options: ["fail", "would fail", "will fail", "are failing"]},
  {q: "The principal warned the students against ______ in the examination hall.", a: "malpractice", options: ["malpractices", "malpractice", "misconducts", "misconduct"]},
  {q: "Choose the word nearly opposite in meaning to the underlined word: The _luxurious_ lifestyle of the king was a contrast to the ______ life of his subjects.", a: "austere", options: ["simple", "austere", "mean", "poor"]},
  {q: "The teacher was very _lenient_ with the students, but the principal was ______.", a: "strict", options: ["hard", "harsh", "strict", "wicked"]},
  {q: "While some people are _extravagant_, others are ______.", a: "frugal", options: ["miserly", "frugal", "poor", "stingy"]},
  {q: "The boy was _timid_, but his sister was ______.", a: "bold", options: ["fearless", "bold", "courageous", "audacious"]},
  {q: "Choose the word nearest in meaning to the underlined word: The _proscription_ of the union was a big blow to the workers.", a: "banning", options: ["launching", "expulsion", "banning", "removal"]},
  {q: "The _strategic_ position of the town made it a target for the enemy.", a: "tactical", options: ["ethical", "practical", "tactical", "legal"]},
  {q: "The instructions were very _explicit_.", a: "clear", options: ["vague", "clear", "brief", "detailed"]},
  {q: "He is a very _versatile_ actor.", a: "talented", options: ["talented", "famous", "popular", "skillful"]},
  {q: "The _alleviation_ of poverty is a major goal of the government.", a: "reduction", options: ["reduction", "removal", "termination", "elimination"]},
  {q: "The students were asked to ______ the passage.", a: "summarize", options: ["summarize", "analyze", "review", "restate"]},
  {q: "The committee has ______ its report.", a: "submitted", options: ["submitted", "presented", "released", "published"]},
  {q: "He was ______ of the theft.", a: "accused", options: ["accused", "charged", "blamed", "suspected"]},
  {q: "The meeting was ______ till next week.", a: "postponed", options: ["cancelled", "delayed", "postponed", "adjourned"]},
  {q: "She ______ to school every day.", a: "walks", options: ["walk", "walks", "walking", "walked"]},
  {q: "The boy ______ the book on the table.", a: "laid", options: ["lay", "laid", "lied", "lain"]},
  {q: "Neither the teacher nor the students ______ present.", a: "were", options: ["is", "was", "are", "were"]},
  {q: "The news ______ very exciting.", a: "is", options: ["is", "are", "were", "be"]},
  {q: "I have ______ my breakfast.", a: "eaten", options: ["eat", "ate", "eaten", "eating"]},
  {q: "The car belongs to ______.", a: "us", options: ["we", "us", "our", "ours"]},
  {q: "He is ______ than his brother.", a: "taller", options: ["tall", "taller", "tallest", "more tall"]},
  {q: "She is the ______ girl in the class.", a: "most beautiful", options: ["beautiful", "more beautiful", "most beautiful", "very beautiful"]},
  {q: "The man ______ stole the money has been caught.", a: "who", options: ["who", "whom", "whose", "which"]},
  {q: "This is the house ______ Jack built.", a: "that", options: ["who", "whom", "that", "which"]},
  {q: "I ______ him for a long time.", a: "have known", options: ["know", "knew", "have known", "had known"]},
  {q: "He ______ to the market yesterday.", a: "went", options: ["go", "goes", "went", "gone"]},
  {q: "The rain ______ when we arrived.", a: "had stopped", options: ["stop", "stops", "stopped", "had stopped"]},
  {q: "If I ______ a bird, I would fly.", a: "were", options: ["am", "was", "were", "be"]},
  {q: "He acts as if he ______ the boss.", a: "were", options: ["is", "was", "were", "be"]},
  {q: "I look forward to ______ you soon.", a: "seeing", options: ["see", "sees", "seeing", "seen"]},
  {q: "The table is made ______ wood.", a: "of", options: ["with", "of", "from", "by"]},
  {q: "He is good ______ Mathematics.", a: "at", options: ["in", "at", "with", "for"]},
  {q: "She is married ______ a doctor.", a: "to", options: ["with", "to", "by", "for"]},
  {q: "The cat is hiding ______ the table.", a: "under", options: ["on", "in", "under", "over"]},
  {q: "He jumped ______ the fence.", a: "over", options: ["over", "across", "through", "on"]},
  {q: "The book is ______ the bag.", a: "in", options: ["on", "in", "at", "by"]},
  {q: "He arrived ______ 10 o'clock.", a: "at", options: ["in", "at", "on", "by"]},
  {q: "She was born ______ 1995.", a: "in", options: ["in", "at", "on", "by"]},
  {q: "The evidence given by the first witness was CONCRETE, but that of the second was ______.", a: "vague", options: ["abstract", "vague", "complex", "unclear"]},
  {q: "While the first sister is known for her HUMILITY, the second is known for her ______.", a: "pride", options: ["arrogance", "pride", "insolence", "vanity"]},
  {q: "The management decided to RETAIN the senior staff and ______ the junior ones.", a: "dismiss", options: ["sack", "dismiss", "expel", "release"]},
  {q: "To prevent a crisis, the government had to RESCIND the law and ______ a new one.", a: "enact", options: ["enact", "produce", "create", "uphold"]},
  {q: "Some people are GULLIBLE, while others are ______.", a: "astute", options: ["skeptical", "shrewd", "astute", "clever"]},
  {q: "The results of the first test were PROVISIONAL, but the second were ______.", a: "final", options: ["conclusive", "final", "permanent", "fixed"]},
  {q: "The soldiers were ordered to ADVANCE, but the commander told the scouts to ______.", a: "retreat", options: ["withdraw", "retreat", "recede", "return"]},
  {q: "While the father is STINGY, the son is ______.", a: "generous", options: ["kind", "generous", "lavish", "wasteful"]},
  {q: "The climate in the north is ARID, but the south is ______.", a: "humid", options: ["wet", "moist", "humid", "damp"]},
  {q: "He is a NOVICE in the game, whereas his brother is a ______.", a: "professional", options: ["master", "professional", "expert", "veteran"]},

  // SECTION: Nearest in Meaning (Synonyms)
  {q: "The principal's speech was very IMPACTFUL.", a: "effective", options: ["touching", "effective", "impressive", "forceful"]},
  {q: "The villagers were AGHAST at the sight of the wreckage.", a: "horrified", options: ["surprised", "horrified", "amazed", "disturbed"]},
  {q: "The manager's decision was ARBITRARY.", a: "random", options: ["unfair", "random", "personal", "hasty"]},
  {q: "The lady is very METICULOUS about her appearance.", a: "careful", options: ["fussy", "careful", "proud", "conscious"]},
  {q: "The witness gave a VIVID account of the accident.", a: "clear", options: ["graphic", "clear", "detailed", "loud"]},
  {q: "The suspect's statement was INCOHERENT.", a: "unclear", options: ["meaningless", "unclear", "confusing", "false"]},
  {q: "The new policy is MANDATORY for all staff.", a: "compulsory", options: ["necessary", "important", "compulsory", "required"]},
  {q: "The heavy rain has SUBSIDED.", a: "lessened", options: ["stopped", "lessened", "ceased", "decreased"]},
  {q: "He is a very RESOURCEFUL person.", a: "inventive", options: ["talented", "inventive", "capable", "skillful"]},
  {q: "The outcome of the election was INEVITABLE.", a: "unavoidable", options: ["certain", "unavoidable", "expected", "clear"]},

  // SECTION: Sentence Completion / Grammar
  {q: "He was accused of ______ the company's funds.", a: "embezzling", options: ["stealing", "embezzling", "taking", "misusing"]},
  {q: "The judge ______ the case for lack of evidence.", a: "dismissed", options: ["cancelled", "dismissed", "closed", "stopped"]},
  {q: "The students were asked to ______ from making noise.", a: "refrain", options: ["abstain", "refrain", "stop", "cease"]},
  {q: "The boy is very good ______ drawing.", a: "at", options: ["in", "at", "with", "on"]},
  {q: "She is the ______ of the two girls.", a: "prettier", options: ["pretty", "prettier", "prettiest", "more pretty"]},
  {q: "Neither the man nor his wife ______ present at the party.", a: "was", options: ["is", "was", "are", "were"]},
  {q: "The driver was warned ______ overspeeding.", a: "against", options: ["on", "of", "against", "from"]},
  {q: "He has been living here ______ ten years.", a: "for", options: ["since", "for", "from", "during"]},
  {q: "If I ______ the money, I would have bought the car.", a: "had had", options: ["have", "had", "had had", "would have"]},
  {q: "The news ______ shared by everyone in the village.", a: "was", options: ["is", "was", "are", "were"]},
  {q: "By the time we arrived, the movie ______.", a: "had started", options: ["starts", "started", "has started", "had started"]},
  {q: "He is one of the players who ______ selected for the team.", a: "were", options: ["is", "was", "are", "were"]},
  {q: "The book is ______ interesting than the one I read last week.", a: "more", options: ["most", "very", "more", "much"]},
  {q: "She preferred dancing ______ singing.", a: "to", options: ["than", "to", "over", "from"]},
  {q: "The teacher made the students ______ the exercise.", a: "do", options: ["do", "to do", "doing", "did"]},
  {q: "The man ______ car was stolen is my uncle.", a: "whose", options: ["who", "whom", "whose", "which"]},
  {q: "I ______ my homework before my father returned.", a: "had finished", options: ["finish", "finished", "have finished", "had finished"]},
  {q: "The car was ______ damaged in the accident.", a: "badly", options: ["bad", "badly", "worse", "worst"]},
  {q: "He didn't go to school because he ______ ill.", a: "was", options: ["is", "was", "has been", "had been"]},
  {q: "The suitcase is ______ heavy for me to carry.", a: "too", options: ["so", "very", "too", "much"]}
],
  "chemistry": [
  /* --- Specific Heat Capacity (SHC) --- */
  // Section 1: Foundations & Atomic Structure
  {q: "Which of the following particles has the least mass?", a: "Electron", options: ["Proton", "Neutron", "Electron", "Alpha particle"]},
  {q: "The number of electrons in the outer shell of an element with atomic number 15 is ______.", a: "5", options: ["2", "3", "5", "8"]},
  {q: "Which of the following elements has the highest first ionization energy?", a: "Helium", options: ["Hydrogen", "Helium", "Lithium", "Neon"]},
  {q: "The movement of liquid molecules from a region of higher concentration to a region of lower concentration is ______.", a: "diffusion", options: ["osmosis", "diffusion", "effusion", "evaporation"]},
  {q: "Which of the following is a physical change?", a: "Melting of ice", options: ["Burning of wood", "Rusting of iron", "Melting of ice", "Souring of milk"]},
  {q: "The relative atomic mass of an element is based on the isotope ______.", a: "Carbon-12", options: ["Carbon-12", "Oxygen-16", "Hydrogen-1", "Nitrogen-14"]},
  {q: "A gas occupies 200cm³ at a pressure of 760mmHg. What is the volume if the pressure is increased to 1000mmHg at constant temperature?", a: "152cm³", options: ["152cm³", "200cm³", "263cm³", "300cm³"]},
  {q: "If the pressure of a fixed mass of gas is doubled, its volume will be ______.", a: "halved", options: ["doubled", "halved", "quadrupled", "unchanged"]},
  {q: "A gas at 2 atm occupies 5dm³. To what pressure must it be subjected to reduce the volume to 2dm³?", a: "5 atm", options: ["2 atm", "4 atm", "5 atm", "10 atm"]},
  {q: "The mathematical expression of Boyle's Law is ______.", a: "PV = k", options: ["V/T = k", "P/T = k", "PV = k", "P = V"]},
  {q: "A sample of gas has a volume of 500cm³ at 700mmHg. What is the pressure when the volume is 250cm³?", a: "1400mmHg", options: ["350mmHg", "700mmHg", "1050mmHg", "1400mmHg"]},
  {q: "Which of the following graphs represents Boyle's Law?", a: "A curve of P against V", options: ["A straight line of P against V", "A curve of P against V", "A straight line of V against T", "A curve of P against T"]},
  {q: "A balloon contains 2.0L of air at 101.3kPa. If the balloon is squeezed to 0.5L, what is the new pressure?", a: "405.2kPa", options: ["50.6kPa", "101.3kPa", "202.6kPa", "405.2kPa"]},
  {q: "Boyle's Law holds true only when ______ is constant.", a: "temperature", options: ["pressure", "volume", "temperature", "mass"]},
  {q: "A gas occupies 15dm³ at a pressure of 1.5 atm. Calculate the volume at standard pressure (1.0 atm).", a: "22.5dm³", options: ["10.0dm³", "15.0dm³", "22.5dm³", "30.0dm³"]},
  {q: "If the volume of a gas is tripled, the pressure will ______.", a: "decrease by one-third", options: ["triple", "decrease by one-third", "remain same", "double"]},
  // Section 2: Bonding & Stoichiometry
  {q: "The bond formed between two elements with a large difference in electronegativity is ______.", a: "ionic", options: ["covalent", "ionic", "metallic", "dative"]},
  {q: "The shape of a water molecule is ______.", a: "bent", options: ["linear", "bent", "tetrahedral", "pyramidal"]},
  {q: "What is the oxidation number of Manganese in KMnO4?", a: "+7", options: ["+2", "+4", "+6", "+7"]},
  {q: "The volume of 0.5 mol of an ideal gas at s.t.p. is ______.", a: "11.2 dm³", options: ["5.6 dm³", "11.2 dm³", "22.4 dm³", "44.8 dm³"]},
  {q: "The formula of the compound formed between Aluminum (Al³⁺) and Oxygen (O²⁻) is ______.", a: "Al2O3", options: ["AlO", "Al2O", "AlO2", "Al2O3"]},
  {q: "Calculate the percentage by mass of Nitrogen in (NH4)2SO4. [N=14, H=1, S=32, O=16]", a: "21.2%", options: ["10.6%", "21.2%", "28.0%", "42.4%"]},

  // Section 3: Gases & Solutions
  {q: "Which of the following gases will bleach damp litmus paper?", a: "Chlorine", options: ["Ammonia", "Chlorine", "Sulphur(IV) oxide", "Carbon(IV) oxide"]},
  {q: "Which of the following is a neutral oxide?", a: "Nitrogen(II) oxide", options: ["Carbon(IV) oxide", "Sulphur(IV) oxide", "Nitrogen(II) oxide", "Sodium oxide"]},
  {q: "The solubility of a gas ______ with an increase in temperature.", a: "decreases", options: ["increases", "decreases", "remains constant", "doubles"]},
  {q: "Which of the following indicators is suitable for the titration of a strong acid against a weak base?", a: "Methyl orange", options: ["Phenolphthalein", "Methyl orange", "Litmus", "Universal indicator"]},
  {q: "Which of the following substances is a sublime solid?", a: "Iodine", options: ["Sodium chloride", "Iodine", "Sugar", "Copper(II) sulphate"]},
  {q: "A gas occupies 100cm³ at 27°C. What will be its volume at 127°C at constant pressure?", a: "133.3cm³", options: ["75cm³", "100cm³", "133.3cm³", "200cm³"]},
  {q: "To convert Celsius to Kelvin, you add ______ to the Celsius value.", a: "273", options: ["100", "273", "373", "0"]},
  {q: "At constant pressure, the volume of a gas is directly proportional to its ______.", a: "absolute temperature", options: ["Celsius temperature", "absolute temperature", "pressure", "density"]},
  {q: "A gas occupies 2.5L at 298K. What is the volume at 350K?", a: "2.94L", options: ["2.12L", "2.50L", "2.94L", "3.20L"]},
  {q: "If a gas at 0°C is heated to 273°C at constant pressure, its volume will ______.", a: "double", options: ["stay the same", "double", "triple", "halve"]},
  {q: "Charles's Law is represented by which formula?", a: "V1/T1 = V2/T2", options: ["P1V1 = P2V2", "V1/T1 = V2/T2", "P1/T1 = P2/T2", "PV = nRT"]},
  {q: "What is the volume of a gas at 400K if it occupied 600cm³ at 300K?", a: "800cm³", options: ["450cm³", "600cm³", "800cm³", "900cm³"]},
  {q: "The temperature at which the volume of an ideal gas becomes zero is ______.", a: "-273°C", options: ["0°C", "273°C", "-273°C", "100°C"]},
  {q: "A gas occupies 150cm³ at 300K. At what temperature will the volume be 300cm³?", a: "600K", options: ["150K", "300K", "450K", "600K"]},
  {q: "The graph of Volume against Absolute Temperature is a ______.", a: "straight line through the origin", options: ["curve", "horizontal line", "straight line through the origin", "vertical line"]},
  // Section 4: Metals & Electrolysis
  {q: "The alloy used in making aircraft parts because of its lightness is ______.", a: "Duralumin", options: ["Brass", "Bronze", "Steel", "Duralumin"]},
  {q: "Which of the following metals is extracted by electrolysis?", a: "Aluminum", options: ["Iron", "Copper", "Aluminum", "Lead"]},
  {q: "The process of losing electrons is called ______.", a: "oxidation", options: ["reduction", "oxidation", "hydrogenation", "neutralization"]},
  {q: "Which of the following is an electrolyte?", a: "Molten sodium chloride", options: ["Sugar solution", "Molten sodium chloride", "Alcohol", "Benzene"]},
  {q: "The most electronegative element is ______.", a: "Fluorine", options: ["Oxygen", "Chlorine", "Fluorine", "Nitrogen"]},
  {q: "The oxidation state of Oxygen in peroxides is ______.", a: "-1", options: ["-2", "-1", "0", "+2"]},
  {q: "The pressure of a gas in a cylinder is 2 atm at 27°C. What will be the pressure at 127°C?", a: "2.67 atm", options: ["1.50 atm", "2.00 atm", "2.67 atm", "4.00 atm"]},
  {q: "Gay-Lussac's Law describes the relationship between ______.", a: "pressure and temperature", options: ["pressure and volume", "volume and temperature", "pressure and temperature", "mass and volume"]},
  {q: "If the absolute temperature of a gas in a rigid container is tripled, the pressure will ______.", a: "triple", options: ["triple", "halve", "stay same", "decrease"]},
  {q: "A gas at 760mmHg and 300K is heated until the pressure is 1520mmHg. What is the new temperature?", a: "600K", options: ["300K", "450K", "600K", "900K"]},
  {q: "Why do aerosol cans carry a warning not to be thrown into fire?", a: "Pressure increases with temperature until it explodes", options: ["The gas disappears", "Pressure increases with temperature until it explodes", "The volume increases", "The can melts"]},
  // Section 5: Organic Chemistry
  {q: "The functional group in alkanols is ______.", a: "-OH", options: ["-CHO", "-COOH", "-OH", "-NH2"]},
  {q: "Which of the following is an example of a saturated hydrocarbon?", a: "Ethane", options: ["Ethene", "Ethyne", "Ethane", "Benzene"]},
  {q: "The main constituent of natural gas is ______.", a: "methane", options: ["ethane", "methane", "propane", "butane"]},
  {q: "The process by which vegetable oils are converted to margarine is ______.", a: "hydrogenation", options: ["saponification", "hydrogenation", "esterification", "hydrolysis"]},
  {q: "Which of the following is a natural polymer?", a: "Cellulose", options: ["Nylon", "Terylene", "Cellulose", "Polythene"]},
  {q: "The reaction between an alkanoic acid and an alkanol is called ______.", a: "esterification", options: ["saponification", "esterification", "hydrolysis", "polymerization"]},

  // Section 6: Reaction Rates & Energetics
  {q: "An increase in the concentration of reactants ______ the rate of a chemical reaction.", a: "increases", options: ["increases", "decreases", "has no effect on", "stops"]},
  {q: "Which of the following is an endothermic process?", a: "Dissolving NH4Cl in water", options: ["Neutralization", "Combustion", "Dissolving NH4Cl in water", "Respiration"]},
  {q: "The catalyst used in the Haber process for the manufacture of ammonia is ______.", a: "Iron", options: ["Platinum", "Iron", "Vanadium(V) oxide", "Nickel"]},
  {q: "The boiling point of water is higher than that of ethanol due to ______.", a: "hydrogen bonding", options: ["van der Waals forces", "hydrogen bonding", "ionic bonding", "metallic bonding"]},
  {q: "The phenomenon whereby an element exists in different forms in the same physical state is ______.", a: "allotropy", options: ["isotopy", "isomerism", "allotropy", "homology"]},

  // Section 7: Acids, Bases & Salts
  {q: "The gas evolved when dilute HCl reacts with Na2CO3 is ______.", a: "Carbon(IV) oxide", options: ["Hydrogen", "Oxygen", "Chlorine", "Carbon(IV) oxide"]},
  {q: "Which of the following is an acidic oxide?", a: "Sulphur(IV) oxide", options: ["Sodium oxide", "Calcium oxide", "Sulphur(IV) oxide", "Magnesium oxide"]},
  {q: "Which of the following is an amphoteric oxide?", a: "Aluminum oxide", options: ["Sodium oxide", "Aluminum oxide", "Carbon(IV) oxide", "Copper(II) oxide"]},
  {q: "What is the pH of a 0.01 mol/dm³ solution of HCl?", a: "2", options: ["1", "2", "7", "14"]},
  {q: "Which of the following salts is insoluble in water?", a: "AgCl", options: ["NaCl", "KNO3", "AgCl", "Ca(HCO3)2"]},
  // Moles and Molar Mass
  {q: "Calculate the molar mass of (NH4)2SO4. [N=14, H=1, S=32, O=16]", a: "132 g/mol", options: ["114 g/mol", "132 g/mol", "126 g/mol", "140 g/mol"]},
  {q: "How many moles are present in 10g of Calcium Carbonate (CaCO3)? [Ca=40, C=12, O=16]", a: "0.10 mol", options: ["0.01 mol", "0.10 mol", "0.50 mol", "1.00 mol"]},
  {q: "What is the percentage by mass of Nitrogen in (NH4)2SO4?", a: "21.2%", options: ["10.6%", "21.2%", "28.0%", "42.4%"]},
  {q: "A compound contains 40% Carbon, 6.7% Hydrogen and 53.3% Oxygen. What is its empirical formula?", a: "CH2O", options: ["CHO", "CH2O", "C2H4O", "CH3O"]},
  {q: "Calculate the number of molecules in 4.4g of CO2. [Avogadro's constant = 6.02 x 10^23]", a: "6.02 x 10^22", options: ["6.02 x 10^23", "6.02 x 10^22", "1.20 x 10^23", "3.01 x 10^22"]},

  // Molarity and Concentrations
  {q: "What is the molarity of a solution containing 4g of NaOH in 250cm³ of solution? [Na=23, O=16, H=1]", a: "0.40 mol/dm³", options: ["0.10 mol/dm³", "0.20 mol/dm³", "0.40 mol/dm³", "0.50 mol/dm³"]},
  {q: "Calculate the mass of KOH required to prepare 500cm³ of 0.1 mol/dm³ solution. [K=39, O=16, H=1]", a: "2.8g", options: ["1.4g", "2.8g", "5.6g", "11.2g"]},
  {q: "What volume of 0.5 mol/dm³ HCl is needed to neutralize 25cm³ of 0.2 mol/dm³ NaOH?", a: "10cm³", options: ["10cm³", "20cm³", "50cm³", "62.5cm³"]},
  {q: "What is the concentration in g/dm³ of a 0.05 mol/dm³ solution of H2SO4? [H=1, S=32, O=16]", a: "4.9g/dm³", options: ["4.9g/dm³", "9.8g/dm³", "2.45g/dm³", "0.49g/dm³"]},
  {q: "A solution has a pH of 2.0. What is the concentration of Hydrogen ions [H+]?", a: "0.01 mol/dm³", options: ["0.1 mol/dm³", "0.01 mol/dm³", "0.001 mol/dm³", "0.02 mol/dm³"]},

  // Stoichiometry (Reacting Masses/Volumes)
  {q: "What volume of Oxygen at s.t.p is required to burn 10cm³ of methane (CH4) completely?", a: "20cm³", options: ["10cm³", "20cm³", "30cm³", "40cm³"]},
  {q: "Calculate the mass of Copper deposited when 6.5g of Zinc reacts with excess CuSO4. [Zn=65, Cu=64]", a: "6.4g", options: ["6.4g", "6.5g", "12.8g", "3.2g"]},
  {q: "What mass of CaCO3 is needed to produce 11.2dm³ of CO2 at s.t.p? [Molar vol = 22.4dm³]", a: "50g", options: ["25g", "50g", "100g", "75g"]},
  {q: "How many moles of H2 are produced when 2 moles of Al react with excess HCl? 2Al + 6HCl -> 2AlCl3 + 3H2", a: "3 moles", options: ["1 mole", "2 moles", "3 moles", "6 moles"]},
  {q: "What is the volume of 0.5 moles of an ideal gas at s.t.p?", a: "11.2 dm³", options: ["5.6 dm³", "11.2 dm³", "22.4 dm³", "44.8 dm³"]},

  // Gas Laws
  {q: "A gas occupies 100cm³ at 27°C. What will be its volume at 127°C if pressure is constant?", a: "133.3cm³", options: ["75cm³", "133.3cm³", "200cm³", "400cm³"]},
  {q: "If the pressure of a gas is doubled at constant temperature, the volume will be ______.", a: "halved", options: ["doubled", "halved", "quadrupled", "unchanged"]},
  {q: "Calculate the pressure of 2 moles of gas in a 10dm³ container at 300K. [R=0.082]", a: "4.92 atm", options: ["2.46 atm", "4.92 atm", "9.84 atm", "1.23 atm"]},
  {q: "A gas cylinder contains 5 moles of Nitrogen and 2 moles of Oxygen. If total pressure is 700mmHg, find the partial pressure of Oxygen.", a: "200 mmHg", options: ["200 mmHg", "500 mmHg", "350 mmHg", "700 mmHg"]},
  {q: "Vapour density of a gas is 15. What is its relative molecular mass?", a: "30", options: ["7.5", "15", "30", "45"]},

  // Electrolysis (Faraday's Laws)
  {q: "What mass of Copper is deposited by 9650 coulombs of electricity? [Cu=64, F=96500C]", a: "3.2g", options: ["0.32g", "3.2g", "6.4g", "32g"]},
  {q: "How many Faradays are required to deposit 1 mole of Aluminum (Al³⁺)?", a: "3F", options: ["1F", "2F", "3F", "6F"]},
  {q: "A current of 2.0A is passed through a silver salt for 10 minutes. Calculate the quantity of electricity.", a: "1200C", options: ["20C", "200C", "1200C", "2400C"]},
  {q: "How long will it take for 5.0A to deposit 0.1 moles of a divalent metal (M²⁺)? [F=96500]", a: "3860s", options: ["1930s", "3860s", "965s", "7720s"]},
  {q: "What volume of Oxygen is liberated at s.t.p by 0.2 Faradays?", a: "1.12 dm³", options: ["1.12 dm³", "2.24 dm³", "5.60 dm³", "11.20 dm³"]},

  // Oxidation & Energy
  {q: "What is the oxidation state of Phosphorus in H3PO4?", a: "+5", options: ["+1", "+3", "+5", "-3"]},
  {q: "Find the oxidation number of Cr in K2Cr2O7.", a: "+6", options: ["+3", "+6", "+7", "+12"]},
  {q: "Calculate the heat of reaction if 50g of water rises from 25°C to 35°C. [c=4.2 J/g/°C]", a: "2100 J", options: ["210 J", "2100 J", "4200 J", "1050 J"]},
  {q: "How many electrons are lost in the half-reaction: Fe²⁺ -> Fe³⁺ + e⁻?", a: "1", options: ["1", "2", "3", "4"]},
  {q: "If 1 mole of ethanol releases 1367kJ on combustion, how much heat is released by 4.6g of ethanol? [Molar mass=46]", a: "136.7 kJ", options: ["13.67 kJ", "136.7 kJ", "1367 kJ", "2734 kJ"]},
  // Section 8: Environmental & Miscellaneous
  {q: "Which of the following is a greenhouse gas?", a: "Methane", options: ["Oxygen", "Nitrogen", "Methane", "Argon"]},
  {q: "The substance used as a lubricant in heavy machinery is ______.", a: "Graphite", options: ["Diamond", "Graphite", "Sulphur", "Phosphorus"]},
  {q: "Which of the following is used in the treatment of hard water?", a: "Sodium carbonate", options: ["Sodium chloride", "Sodium carbonate", "Calcium sulphate", "Magnesium chloride"]},
  {q: "The major constituent of steel is ______.", a: "Iron", options: ["Copper", "Iron", "Aluminum", "Zinc"]},
  {q: "Which of the following indicators is red in acidic medium?", a: "Methyl orange", options: ["Phenolphthalein", "Methyl orange", "Litmus", "Bromothymol blue"]},
  {q: "Which of the following is used as a fuel in nuclear reactors?", a: "Uranium", options: ["Uranium", "Thorium", "Plutonium", "Radium"]},
  {q: "The gas that turns lime water milky is ______.", a: "CO2", options: ["O2", "N2", "CO2", "H2"]},
  {q: "Which of the following is a member of the halogen family?", a: "Bromine", options: ["Sodium", "Magnesium", "Bromine", "Neon"]},
  {q: "The standard electrode potential is measured at ______.", a: "298 K", options: ["273 K", "298 K", "373 K", "0 K"]},
  {q: "Which of the following rays has the highest penetrating power?", a: "Gamma rays", options: ["Alpha rays", "Beta rays", "Gamma rays", "X-rays"]},
  {q: "The raw materials for the manufacture of soap are ______.", a: "fats and alkalis", options: ["fats and acids", "fats and alkalis", "sugar and yeast", "petroleum and water"]}
]
};